import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 主要的介绍页面和整体导航
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '💎 Wealth',
      link: {
        type: 'doc',
        id: 'wealth/index',
      },
      items: [{type: 'autogenerated', dirName: 'wealth'}],
    },
    {
      type: 'category',
      label: '📢 Influence',
      link: {
        type: 'doc',
        id: 'influence/index',
      },
      items: [{type: 'autogenerated', dirName: 'influence'}],
    },
    {
      type: 'category',
      label: '🛠️ Build',
      link: {
        type: 'doc',
        id: 'build/index',
      },
      items: [{type: 'autogenerated', dirName: 'build'}],
    },
  ],

  // Wealth 专门的侧边栏
  wealthSidebar: [
    'wealth/index',
    {type: 'autogenerated', dirName: 'wealth'},
  ],

  // Influence 专门的侧边栏
  influenceSidebar: [
    'influence/index',
    {type: 'autogenerated', dirName: 'influence'},
  ],

  // Build 专门的侧边栏
  buildSidebar: [
    'build/index',
    {type: 'autogenerated', dirName: 'build'},
  ],
};

export default sidebars;
